dist: xenial
language: c
compiler:
  - gcc
  - clang

env:
  - CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF"
  - CMAKE_ARGS="-DBUILD_SHARED_LIBS=ON"
  - CMAKE_ARGS="-DSODIUM_MINIMAL=ON"

script:
  - mkdir build && cd build
  - cmake .. ${CMAKE_ARGS}
  - make -j
  - ctest -j
